=== rasmimihub/WEBLab-Report2/Practice.dtd
<!ELEMENT students (students+)>
<!ELEMENT student (name,phone,email,college,program,duration)>
<!ATTLIST student id CDATA #REQUIRED>
<!ELEMENT name(first,middle?,last>
<!ATTLIST name title (mr | mrs | ms) "ms">
<!ELEMENT first (# PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT college(c_name,address,website)>
<!ELEMENT c_name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT program (#PCDATA)>
<!ATTLIST program type (year | semester) "year">
<!ELEMENT duration (#PCDATA)>

=== rasmimihub/WEBLab-Report2/Practice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students  SYSTEM  "Practice.dtd">
<students>
     <student id="101">
      <name title="ms">
        <first>Rashmi</first>
        <middle></middle>
        <last>Pariyar</last>
      </name>
      <phone type="personal">98xxxxxxxx</phone>
      <email>rasmi@gmail.com</email>
           <college id="57">
          <c_name>Padmakanya Multiple Campus</c_name>
          <address>Swoyambhu</address>
          <website>www.rasmi.com.np</website>
        </college>
        <program type="semester">BCA</program>
        <duration>Two year</duration>
    </student>
    
    <student id="102">
        <name title="ms">
            <first>Alisha</first>
            <middle></middle>
            <last>Limbu</last>
        </name>
        <phone type="personal">98xxxxxxxxx</phone>
        <email>alisha2@gmail.com</email>
            <college id="1">
            <c_name>Padmakanya Multiple Campus</c_name>
            <address>Kalanki</address>
          <website>www.alishaaa.com.np</website>
        <program type="semester">BCA</program>
        <duration>Two year</duration>
            </college>
    </student>
  </students>
