=== rasmimihub/WEBLab-Report2/Question7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Movie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="year" type="xs:string"/>
                <xs:element name="_director">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="_directorname" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element name="comment">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="lang" type="xs:string" use="optional"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="newcomment" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rasmimihub/WEBLab-Report2/Question7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Question7.xsd">
<Movie id="m001">
<title>Aaa mero hajur</title>
<year>2078</year>
<_director>
<_directorname>mr binod bista</_directorname>
</_director>
<comment type="en">it was amazing</comment>
<newcomment>amazing</newcomment>
</Movie>
<Movie id="m089">
<title>golmaal</title>
<year>July 14, 2006</year>
<_director>
<_directorname>Rohit Shetty</_directorname>
</_director>
<comment type="en">it was fun and comedy at the same time</comment>
<newcomment>amazing</newcomment>
</Movie>
</Movies>
