=== rasmimihub/WEBLab-Report2/Question6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="location" type="xs:string"/>
                            <xs:element name="staffCollection">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="staff" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="title" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="addresses">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="address" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="street" type="xs:string"/>
                                                                            <xs:element name="suburb" type="xs:string"/>
                                                                            <xs:element name="postcode" type="xs:string"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="staffId" type="xs:string" use="required"/>
                                                <xs:attribute name="category" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="academic"/>
                                                            <xs:enumeration value="general"/>
                                                            <xs:enumeration value="technical"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="subjectCollection">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                    <xs:element name="capacity">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="6"/> <!-- Minimum students for subject -->
                                                                <xs:maxInclusive value="400"/> <!-- Maximum allowed -->
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="subjectCode" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sid" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rasmimihub/WEBLab-Report2/Question6.xml
<?xml version="1.0" encoding="UTF-8"?>
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Question6.xsd">
<school sid="SCH001">
<name>Padma kanya multiple campus</name>
<location>Kathmandu, Nepal</location>
<staffCollection>
<staff staffId="STF001" category="academic">
<name>Ramesh Thapa</name>
<title>Professor</title>
<addresses>
<address>
<street>Main Road</street>
<suburb>Kathmandu</suburb>
<postcode>44600</postcode>
</address>
<address>
<street>Ring Road</street>
<suburb>Bhaktapur</suburb>
<postcode>44800</postcode>
</address>
</addresses>
</staff>
<staff staffId="STF002" category="technical">
<name>Hari Bahadur</name>
<addresses>
<address>
<street>Naya Bazaar</street>
<suburb>Patan</suburb>
<postcode>44700</postcode>
</address>
</addresses>
</staff>
</staffCollection>
<subjectCollection>
<subject subjectCode="CS101">
<name>Introduction to Programming</name>
<description>Application design using programming language python.</description>
<capacity>60</capacity>
</subject>
<subject subjectCode="CS102">
<name>Database Management</name>
<description>manage database of company</description>
<capacity>70</capacity>
<!--  This subject will be canceled  -->
</subject>
</subjectCollection>
</school>
</university>
