=== rasmimihub/WEBLab-Report2/Question15.dtd
<!ELEMENT Employees (Employee+)>
<!ELEMENT Employee (Post, Salary, Gender, UserName, Password)>

<!ELEMENT Post (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT UserName (#PCDATA)>
<!ELEMENT Password (#PCDATA)>

<!ATTLIST Employee id ID #REQUIRED>

<!ATTLIST UserName minlength CDATA "8">
<!ATTLIST Post minlength CDATA "5" maxlength CDATA "8">
<!ATTLIST Password minlength CDATA "8">
<!ATTLIST Password pattern CDATA "[A-Z][a-z][0-9]{6}">
<!ATTLIST Gender (male | female | others) #REQUIRED>
<!ATTLIST Salary min CDATA "25000" max CDATA "50000">

=== rasmimihub/WEBLab-Report2/Question15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees SYSTEM "Question15.dtd">
<Employees>
    <Employee id="E001">
        <Post>Manager</Post>
        <Salary>30000</Salary>
        <Gender>male</Gender>
        <UserName>johnsmith</UserName>
        <Password>Aa123456</Password>
    </Employee>
    <Employee id="E002">
        <Post>Clerk</Post>
        <Salary>25000</Salary>
        <Gender>female</Gender>
        <UserName>janedoe12</UserName>
        <Password >Ab987654</Password>
    </Employee>
    <Employee id="E003">
        <Post>Admin</Post>
        <Salary>45000</Salary>
        <Gender>others</Gender>
        <UserName>adminuser</UserName>
        <Password>Ac135790</Password>
    </Employee>
    <Employee id="E004">
        <Post>Sales</Post>
        <Salary>40000</Salary>
        <Gender>male</Gender>
        <UserName>saleslead</UserName>
        <Password>Ad567123</Password>
    </Employee>
    <Employee id="E005">
        <Post>HR</Post>
        <Salary>50000</Salary>
        <Gender>female</Gender>
        <UserName>hrmanager</UserName>
        <Password>Ae345678</Password>
    </Employee>
</Employees>
